version: '3'
services:

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "admin"

